export const sampleDataShop = [
    {
        id: 1,
        name: "Rounded Red Hat",
        price: "8.00",
        image: "shop1.png",
        colorOptions: ["#B1C5D4", "#063E66"],
    },
    {
        id: 2,
        name: "Linen Plain Top",
        price: "17.00",
        image: "shop2.png",
        colorOptions: ["#C1E1C1", "#000000"],
    },
    {
        id: 3,
        name: "Oversized T-shirt",
        price: "106.00",
        image: "shop3.png",
        colorOptions: ["#FFD1DC", "#C6AEC7", "#FFFFFF"],
    },
    {
        id: 4,
        name: "Boxy Denim Hat",
        price: "25.00",
        image: "shop4.png",
        colorOptions: ["#B1C5D4", "#063E66"],
    },
    {
        id: 5,
        name: "Linen Plain Top",
        price: "25.00",
        image: "shop5.png",
        colorOptions: ["#C1E1C1", "#000000"],
    },
    {
        id: 6,
        name: "Oversized T-shirt",
        price: "11.00",
        image: "shop6.png",
        colorOptions: ["#FFD1DC", "#C6AEC7", "#FFFFFF"],
    },
    {
        id: 7,
        name: "Polarised Sunglasses",
        price: "18.00",
        image: "shop7.png",
        colorOptions: ["#000000", "#836953"],
    },
    {
        id: 8,
        name: "Rockstar Jacket",
        price: "22.00",
        image: "shop8.png",
        colorOptions: ["#C6AEC7", "#BEDCE3"],
    },
    {
        id: 9,
        name: "Dotted Black Dress",
        price: "20.00",
        image: "shop9.png",
        colorOptions: ["#063E66", "#000000", "#B1C5D4"],
    },

]